#nullable enable
namespace FarmSim.Images.Tropical.Assets;
public static class PngImageAssets
{
    public const string Bakery = "Bakery";
    public const string BeachfrontGrill = "BeachfrontGrill";
    public const string BeachfrontKitchen = "BeachfrontKitchen";
    public const string BlueCrystal = "BlueCrystal";
    public const string Boar = "Boar";
    public const string Ceviche = "Ceviche";
    public const string Chicken = "Chicken";
    public const string Clay = "Clay";
    public const string CocoaPod = "CocoaPod";
    public const string CocoaPowder = "CocoaPowder";
    public const string Coconut = "Coconut";
    public const string CorelReef = "CorelReef";
    public const string Crab = "Crab";
    public const string CrabRoll = "CrabRoll";
    public const string CraftWorkstation = "CraftWorkstation";
    public const string Dolphin = "Dolphin";
    public const string Egg = "Egg";
    public const string EggRoll = "EggRoll";
    public const string Ethan = "Ethan";
    public const string Fiona = "Fiona";
    public const string Fish = "Fish";
    public const string FishRoll = "FishRoll";
    public const string Flour = "Flour";
    public const string FriedRice = "FriedRice";
    public const string FruitPress = "FruitPress";
    public const string Geode = "Geode";
    public const string George = "George";
    public const string Glassworks = "Glassworks";
    public const string Grill = "Grill";
    public const string GrilledCrab = "GrilledCrab";
    public const string HotSprings = "HotSprings";
    public const string HuluHut = "HuluHut";
    public const string IronOre = "IronOre";
    public const string Jasmine = "Jasmine";
    public const string Kai = "Kai";
    public const string Kiko = "Kiko";
    public const string Lime = "Lime";
    public const string Lobster = "Lobster";
    public const string LobsterRoll = "LobsterRoll";
    public const string Luna = "Luna";
    public const string Mushroom = "Mushroom";
    public const string OrangeCrystal = "OrangeCrystal";
    public const string Orchid = "Orchid";
    public const string PinaColada = "PinaColada";
    public const string Pineapple = "Pineapple";
    public const string PineappleSmoothie = "PineappleSmoothie";
    public const string PurpleCrystal = "PurpleCrystal";
    public const string Rice = "Rice";
    public const string ScentedCandle = "ScentedCandle";
    public const string SearedFish = "SearedFish";
    public const string Seashell = "Seashell";
    public const string Silo = "Silo";
    public const string SilverOre = "SilverOre";
    public const string SmugglersCave = "SmugglersCave";
    public const string SteamedRice = "SteamedRice";
    public const string Sugar = "Sugar";
    public const string SushiStand = "SushiStand";
    public const string Tapicoa = "Tapicoa";
    public const string Toby = "Toby";
    public const string TruffleFries = "TruffleFries";
    public const string Vanilla = "Vanilla";
    public const string Zazu = "Zazu";
    public static void Register()
    {
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Bakery", "/_content/FarmSim.Images.Tropical/Bakery.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("BeachfrontGrill", "/_content/FarmSim.Images.Tropical/BeachfrontGrill.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("BeachfrontKitchen", "/_content/FarmSim.Images.Tropical/BeachfrontKitchen.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("BlueCrystal", "/_content/FarmSim.Images.Tropical/BlueCrystal.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Boar", "/_content/FarmSim.Images.Tropical/Boar.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Ceviche", "/_content/FarmSim.Images.Tropical/Ceviche.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Chicken", "/_content/FarmSim.Images.Tropical/Chicken.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Clay", "/_content/FarmSim.Images.Tropical/Clay.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("CocoaPod", "/_content/FarmSim.Images.Tropical/CocoaPod.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("CocoaPowder", "/_content/FarmSim.Images.Tropical/CocoaPowder.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Coconut", "/_content/FarmSim.Images.Tropical/Coconut.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("CorelReef", "/_content/FarmSim.Images.Tropical/CorelReef.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Crab", "/_content/FarmSim.Images.Tropical/Crab.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("CrabRoll", "/_content/FarmSim.Images.Tropical/CrabRoll.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("CraftWorkstation", "/_content/FarmSim.Images.Tropical/CraftWorkstation.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Dolphin", "/_content/FarmSim.Images.Tropical/Dolphin.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Egg", "/_content/FarmSim.Images.Tropical/Egg.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("EggRoll", "/_content/FarmSim.Images.Tropical/EggRoll.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Ethan", "/_content/FarmSim.Images.Tropical/Ethan.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Fiona", "/_content/FarmSim.Images.Tropical/Fiona.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Fish", "/_content/FarmSim.Images.Tropical/Fish.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("FishRoll", "/_content/FarmSim.Images.Tropical/FishRoll.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Flour", "/_content/FarmSim.Images.Tropical/Flour.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("FriedRice", "/_content/FarmSim.Images.Tropical/FriedRice.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("FruitPress", "/_content/FarmSim.Images.Tropical/FruitPress.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Geode", "/_content/FarmSim.Images.Tropical/Geode.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("George", "/_content/FarmSim.Images.Tropical/George.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Glassworks", "/_content/FarmSim.Images.Tropical/Glassworks.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Grill", "/_content/FarmSim.Images.Tropical/Grill.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("GrilledCrab", "/_content/FarmSim.Images.Tropical/GrilledCrab.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("HotSprings", "/_content/FarmSim.Images.Tropical/HotSprings.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("HuluHut", "/_content/FarmSim.Images.Tropical/HuluHut.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("IronOre", "/_content/FarmSim.Images.Tropical/IronOre.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Jasmine", "/_content/FarmSim.Images.Tropical/Jasmine.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Kai", "/_content/FarmSim.Images.Tropical/Kai.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Kiko", "/_content/FarmSim.Images.Tropical/Kiko.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Lime", "/_content/FarmSim.Images.Tropical/Lime.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Lobster", "/_content/FarmSim.Images.Tropical/Lobster.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("LobsterRoll", "/_content/FarmSim.Images.Tropical/LobsterRoll.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Luna", "/_content/FarmSim.Images.Tropical/Luna.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Mushroom", "/_content/FarmSim.Images.Tropical/Mushroom.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("OrangeCrystal", "/_content/FarmSim.Images.Tropical/OrangeCrystal.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Orchid", "/_content/FarmSim.Images.Tropical/Orchid.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("PinaColada", "/_content/FarmSim.Images.Tropical/PinaColada.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Pineapple", "/_content/FarmSim.Images.Tropical/Pineapple.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("PineappleSmoothie", "/_content/FarmSim.Images.Tropical/PineappleSmoothie.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("PurpleCrystal", "/_content/FarmSim.Images.Tropical/PurpleCrystal.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Rice", "/_content/FarmSim.Images.Tropical/Rice.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("ScentedCandle", "/_content/FarmSim.Images.Tropical/ScentedCandle.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("SearedFish", "/_content/FarmSim.Images.Tropical/SearedFish.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Seashell", "/_content/FarmSim.Images.Tropical/Seashell.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Silo", "/_content/FarmSim.Images.Tropical/Silo.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("SilverOre", "/_content/FarmSim.Images.Tropical/SilverOre.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("SmugglersCave", "/_content/FarmSim.Images.Tropical/SmugglersCave.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("SteamedRice", "/_content/FarmSim.Images.Tropical/SteamedRice.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Sugar", "/_content/FarmSim.Images.Tropical/Sugar.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("SushiStand", "/_content/FarmSim.Images.Tropical/SushiStand.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Tapicoa", "/_content/FarmSim.Images.Tropical/Tapicoa.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Toby", "/_content/FarmSim.Images.Tropical/Toby.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("TruffleFries", "/_content/FarmSim.Images.Tropical/TruffleFries.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Vanilla", "/_content/FarmSim.Images.Tropical/Vanilla.png");
        CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileContentRegistry.RegisterFile("Zazu", "/_content/FarmSim.Images.Tropical/Zazu.png");
    }
}